### ISSUE TITLE
Ignoring the last block of ResNet

### ISSUE THREAD

**Issue by pesekon2** [srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0#28]
On [this line](https://github.com/srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0/blob/master/deeplab.py#L69), you pass the layer `actinvation_39` to `ASPP`. As far as I can see from the code, it corresponds to the last layer of block 4. 

Is that a bug, or is there any reason to ignore the last block of ResNet? I have tried to find any info on this in the original paper, but it seems to me like they have normally used all blocks of ResNet.

**Comment by srihari-humbarwadi** [comment]
We use resnet as a feature extractor to construct the segmentation model. Specifically, we use `activation_9` and `activation_39`.  
> I have tried to find any info on this in the original paper, but it seems to me like they have normally used all blocks of ResNet.

No block is left out since `activation_39` is layer from the last block

**Comment by pesekon2** [comment]
Ah okay, then probably it was a mistake in my counting as it really seemed to me like `activation_39` is the last layer of the fourth block and not the fifth one.

**Comment by srihari-humbarwadi** [comment]
I need to correct myself.
We use features from the last layer of block4 (`activation_39`) since the stride at the end of block4 is 16.
```
For the task of image classification, the spatial resolution of the
final feature maps is usually 32 times smaller than the input image resolution and
thus output stride = 32. For the task of semantic segmentation, one can adopt
output stride = 16 (or 8) for denser feature extraction by removing the striding
in the last one (or two) block(s) ...
```
The paper does say,  we could remove the strided conv2d layers in block5 (which is at stride 32), to make it stride 16 and then use it to build the model. I did not do that since I was planning to use the ResNet50 from `keras_applications`

This implementation is getting a do-over soon to make it compatible with the latest tensorflow release. Thanks for pointing this out! @pesekon2

**Comment by pesekon2** [comment]
Great, now I understand that. Thanks!
